package:
  name: "open3spn2"
  version: "0.1.3"

source:
  git_url: https://github.com/cabb99/open3spn2.git
  git_rev: 0.1.3
  git_depth: 5 # (Defaults to -1/not shallow)

build:
  number: 0
  script: python setup.py install --record=record.txt

requirements:
  host:
    - biopython
    - mdtraj
    - nose
    - numpy>=1.16.2
    - openmm
    - pandas
    - parmed
    - pdbfixer
    - pip
    - python
    - scipy
  run:
    - biopython
    - mdtraj
    - nose
    - numpy
    - openmm
    - pandas
    - parmed
    - pdbfixer
    - python
    - scipy

test:
  imports:
    - open3SPN2

about:
  home: "https://github.com/cabb99/open3spn2"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Implementation of 3SPN2 and 3SPN2.C forcefields in openmm"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - cabb99
